[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
#see https://github.com/rustwasm/wasm-pack/issues/886#issuecomment-689597345
wasm-bindgen = "^0.2.60"
web-sys = "=0.3.37"
notecalc = { path = "../notecalc" }
byteorder = "1.3.4"
flate2 = "^1.0.19"
base64 = "0.13.0"
bumpalo = "3.4.0"

# The `console_error_panic_hook` crate provides better debugging of
# panics by logging them with `console.error`.
# This is great for development, but requires the entire
# `std::fmt` and `std::panicking` infrastructure,
# which is not good for code size on deployment.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm,
# with a code size of only ~1K compared to ~10K for the default allocator.
# However, it is slower than the default allocator.
# Unfortunately, so far `wee_alloc` requires night Rust when working with wasm.
wee_alloc = { version = "0.4.2", optional = true }
